app:
  name: axonserver
  platform: "ee"

statefulset:
  replicas: 3
  container:
    image: "axoniq/axonserver"
    pullPolicy: Always

  readiness:
    initialDelaySeconds: 120
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 30

  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

volumeClaimTemplates:
  events:
    accessModes: "ReadWriteOnce"
    storage: 5Gi
  log:
    accessModes: "ReadWriteOnce"
    storage: 1Gi
  data:
    accessModes: "ReadWriteOnce"
    storage: 1Gi

axoniq:
  licenseBase64: ""
  axonserver:
    systemToken: ""
    properties:
      logging:
        maxHistory: 10
        maxSize: 10MB
    propertiesBase64: ""
    clusterTemplateBase64: ""
    admin:
      userName: "admin"
      password: ""
    
service:
  ports:
    grpc: "8124"
    gui: "8024"

ingress:
  host: ""
  annotations: {}
  tls_secret: axonserver-tls
