app:
  name: axonserver
  platform: "se"

statefulset:
  replicas: 3
  container:
    image: "axoniq/axonserver"
    pullPolicy: Always

  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 30
    exec:
      command: "java -jar axonserver-cli.jar contexts -t $(cat ./config/axonserver.token)"

  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

volumeClaimTemplates:
  events:
    accessModes: "ReadWriteOnce"
    storage: 5Gi
  data:
    accessModes: "ReadWriteOnce"
    storage: 1Gi

service:
  ports:
    grpc: "8124"
    gui: "8024"

ingress:
  host: ""
  annotations:
    cert-manager.io/cluster-issuer: ""
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: balanced
  tls_secret: axonserver-tls
