---
{{ range .Values.issuers }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    server: {{ .server }}
    privateKeySecretRef:
      name: {{ .privateKeySecretRef.name | default .name }}
    externalAccountBinding:
      keyID: {{ $.Values.keyId }}
      keySecretRef:
        name: zero-sll-eabsecret
        key: secret
      keyAlgorithm: HS256
    solvers:
      {{ .solvers | toYaml | indent 6 | trim }}
{{ end }}
