---
issuers:
  - name: letsencrypt
    email: ""
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: "nginx"
