{{- range untilStep 0 (int .Values.statefulset.count) 1 }}
{{ if and ($.Values.volumeClaimTemplates.data.enabled) ($.Values.volumeClaimTemplates.data.volumeIds) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $.Release.Namespace }}
  name: data-axonserver-{{ . }} 
spec:
  volumeName: data-axonserver-{{ . }} 
  accessModes:
    {{ toYaml $.Values.volumeClaimTemplates.data.accessModes | nindent 4 }}
  storageClassName: {{ $.Values.volumeClaimTemplates.storageClassName  }}
  resources:
    requests:
      storage: {{$.Values.volumeClaimTemplates.data.storage}} 
{{ end }}

{{ if and ($.Values.volumeClaimTemplates.events.enabled) ($.Values.volumeClaimTemplates.data.volumeIds) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $.Release.Namespace }}
  name: events-axonserver-{{ . }} 
spec:
  volumeName: events-axonserver-{{ . }} 
  accessModes:
    {{ toYaml $.Values.volumeClaimTemplates.events.accessModes | nindent 4 }}
  storageClassName: {{ $.Values.volumeClaimTemplates.storageClassName  }}
  resources:
    requests:
      storage: {{$.Values.volumeClaimTemplates.events.storage}} 
{{ end }}

{{ if and ($.Values.volumeClaimTemplates.exts.enabled) ($.Values.volumeClaimTemplates.data.volumeIds) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $.Release.Namespace }}
  name: exts-axonserver-{{ . }} 
spec:
  volumeName: exts-axonserver-{{ . }} 
  accessModes:
    {{ toYaml $.Values.volumeClaimTemplates.exts.accessModes | nindent 4 }}
  storageClassName: {{ $.Values.volumeClaimTemplates.storageClassName  }}
  resources:
    requests:
      storage: {{$.Values.volumeClaimTemplates.exts.storage}} 
{{ end }}

{{ if and ($.Values.volumeClaimTemplates.plugins.enabled) ($.Values.volumeClaimTemplates.data.volumeIds) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $.Release.Namespace }}
  name: plugins-axonserver-{{ . }} 
spec:
  volumeName: plugins-axonserver-{{ . }} 
  accessModes:
    {{ toYaml $.Values.volumeClaimTemplates.plugins.accessModes | nindent 4 }}
  storageClassName: {{ $.Values.volumeClaimTemplates.storageClassName  }}
  resources:
    requests:
      storage: {{$.Values.volumeClaimTemplates.plugins.storage}} 
{{ end }}

{{ if and ($.Values.volumeClaimTemplates.snapshots.enabled) ($.Values.volumeClaimTemplates.data.volumeIds) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $.Release.Namespace }}
  name: snapshots-axonserver-{{ . }} 
spec:
  volumeName: snapshots-axonserver-{{ . }} 
  accessModes:
    {{ toYaml $.Values.volumeClaimTemplates.snapshots.accessModes | nindent 4 }}
  storageClassName: {{ $.Values.volumeClaimTemplates.storageClassName  }}
  resources:
    requests:
      storage: {{$.Values.volumeClaimTemplates.snapshots.storage}} 
{{ end }}
{{- end }}