---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-gui
  labels:
    app: {{.Values.app.name}}
spec:
  ports:
  - name: gui
    port: {{ .Values.service.ports.gui }}
    targetPort: {{ .Values.service.ports.gui }}
  sessionAffinity: ClientIP
  selector:
    app: {{.Values.app.name}}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-svc
  labels:
    app: {{.Values.app.name}}
spec:
  ports:
  - name: grpc
    port: {{ .Values.service.ports.grpc }}
    targetPort: {{ .Values.service.ports.grpc }}
  - name: internal-grpc
    port: 8224
    targetPort: 8224
  selector:
    app: {{.Values.app.name}}
  type: ClusterIP
  clusterIP: None
  