apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.app.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  serviceName: {{.Values.app.name}}-grpc
  {{if eq .Values.app.platform "ee"}}
  replicas: {{.Values.statefulset.replicas}}
  {{else}}
  replicas: 1
  {{end}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: {{.Values.app.name}}
        image: {{.Values.statefulset.container.image}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: {{ .Values.service.ports.grpc }}
          protocol: TCP
        - name: gui
          containerPort: {{ .Values.service.ports.gui }}
          protocol: TCP
        {{if eq .Values.app.platform "ee"}}
        env: 
        {{- range .Values.statefulset.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        - name: AXONIQ_LICENSE
          value: {{.Values.statefulset.container.workdir }}/license/axoniq.license
        {{end}}
        volumeMounts:
        - name: log
          mountPath: {{.Values.statefulset.container.workdir }}/log
        - name: data
          mountPath: {{.Values.statefulset.container.workdir }}/data
        - name: snapshots
          mountPath: {{.Values.statefulset.container.workdir }}/snapshots
        - name: events
          mountPath: {{.Values.statefulset.container.workdir }}/events
        {{if eq .Values.app.platform "ee"}}  
        - name: properties
          mountPath: {{.Values.statefulset.container.workdir }}/config/axonserver.properties
          subPath: axonserver.properties
          readOnly: true
        - name: cluster-template
          mountPath: {{.Values.statefulset.container.workdir }}/config/cluster-template.yaml
          subPath: cluster-template.yaml
          readOnly: true
        - name: system-token
          mountPath: {{.Values.statefulset.container.workdir }}/security/axoniq.token
          subPath: axoniq.token
          readOnly: true
        - name: license
          mountPath: {{.Values.statefulset.container.workdir }}/license/axoniq.license
          subPath: axoniq.license
          readOnly: true
        {{end}}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.ports.gui }}
          initialDelaySeconds: {{.Values.statefulset.readiness.initialDelaySeconds}}
          periodSeconds: {{.Values.statefulset.readiness.periodSeconds}}
          timeoutSeconds: {{.Values.statefulset.readiness.timeoutSeconds}}
          failureThreshold: {{.Values.statefulset.readiness.failureThreshold}}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.ports.gui }}
          initialDelaySeconds: {{.Values.statefulset.liveness.initialDelaySeconds}}
          periodSeconds: {{.Values.statefulset.liveness.periodSeconds}}
          timeoutSeconds: {{.Values.statefulset.liveness.timeoutSeconds}}
          successThreshold: {{.Values.statefulset.liveness.successThreshold}}
          failureThreshold: {{.Values.statefulset.liveness.failureThreshold}}
      volumes:
        - name: log
          emptyDir: {}
        {{if eq .Values.app.platform "ee"}}  
        - name: properties
          secret:
            secretName: axonserver-properties
        - name: cluster-template
          secret:
            secretName: axonserver-cluster-template
        - name: system-token
          secret:
            secretName: axonserver-system-token
        - name: license
          secret:
            secretName: axonserver-license
        {{end}}
  volumeClaimTemplates:
    - metadata:
        name: events
      spec:
        accessModes:
          {{ toYaml .Values.volumeClaimTemplates.events.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{.Values.volumeClaimTemplates.events.storage}}
    - metadata:
        name: data
      spec:
        accessModes:
          {{ toYaml .Values.volumeClaimTemplates.data.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{.Values.volumeClaimTemplates.data.storage}}
    - metadata:
        name: snapshots
      spec:
        accessModes: 
          {{ toYaml .Values.volumeClaimTemplates.snapshots.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{.Values.volumeClaimTemplates.snapshots.storage}}
