{{ range untilStep 0 (int .Values.statefulset.count) 1 }}
{{ $counter := . }}
{{ $appName := $.Values.app.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$appName}}-{{ $counter }}
  labels:
    app: {{$appName}}
    sts: {{$appName}}-{{$counter}}
spec:
  podManagementPolicy: {{$.Values.statefulset.podManagementPolicy}}
  serviceName: {{$appName}}-svc
  updateStrategy:
    type: {{ $.Values.statefulset.updateStrategy.type }}
  replicas: 1
  selector:
    matchLabels:
      app: {{$appName}}
  template:
    metadata:
      labels:
        app: {{$appName}}
        sts: {{$appName}}-{{$counter}}
        {{- with $.Values.podLabels }}{{ . | trim | nindent 8 }}{{- end }}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | indent 8 }}
      {{ if $.Values.aws.azs }}
        {{ with index $.Values.aws.azs $counter }}
        topology.kubernetes.io/zone: {{ . }}
        {{ end }}
      {{ end }}
      containers:
      - name: {{$appName}}
        image: {{$.Values.statefulset.container.image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{$.Values.resources.limits.cpu}}
            memory: {{$.Values.resources.limits.memory}}
          requests:
            cpu: {{$.Values.resources.requests.cpu}}
            memory: {{$.Values.resources.requests.memory}}
        ports:
        - name: grpc
          containerPort: {{$.Values.service.ports.grpc}}
          protocol: TCP
        - name: gui
          containerPort: {{$.Values.service.ports.gui}}
          protocol: TCP
        {{if eq $.Values.app.platform "ee"}}
        env:
        {{ range $.Values.statefulset.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{ end }}
        - name: AXONIQ_LICENSE
          value: {{$.Values.statefulset.container.workdir }}/license/axoniq.license
        {{end}}
        readinessProbe:
          tcpSocket:
            port: {{ $.Values.service.ports.gui }}
          initialDelaySeconds: {{$.Values.statefulset.readiness.initialDelaySeconds}}
          periodSeconds: {{$.Values.statefulset.readiness.periodSeconds}}
          timeoutSeconds: {{$.Values.statefulset.readiness.timeoutSeconds}}
          successThreshold: {{$.Values.statefulset.readiness.successThreshold}}
          failureThreshold: {{$.Values.statefulset.readiness.failureThreshold}}
        livenessProbe:
          tcpSocket:
            port: {{ $.Values.service.ports.gui }}
          initialDelaySeconds: {{$.Values.statefulset.liveness.initialDelaySeconds}}
          periodSeconds: {{$.Values.statefulset.liveness.periodSeconds}}
          timeoutSeconds: {{$.Values.statefulset.liveness.timeoutSeconds}}
          successThreshold: {{$.Values.statefulset.liveness.successThreshold}}
          failureThreshold: {{$.Values.statefulset.liveness.failureThreshold}}
        
        volumeMounts:
        {{range $k, $v := $.Values.volumeClaimTemplates.templates}}
        - name: {{$k}}
          mountPath: {{ printf "%s/%s" $.Values.statefulset.container.workdir $k }}
        {{end}}
        {{if eq $.Values.app.platform "ee"}}
        - name: properties
          mountPath: {{$.Values.statefulset.container.workdir }}/config/axonserver.properties
          subPath: axonserver.properties
          readOnly: true
        - name: cluster-template
          mountPath: {{$.Values.statefulset.container.workdir }}/config/cluster-template.yaml
          subPath: cluster-template.yaml
          readOnly: true
        - name: system-token
          mountPath: {{$.Values.statefulset.container.workdir }}/security/axoniq.token
          subPath: axoniq.token
          readOnly: true
        - name: license
          mountPath: {{$.Values.statefulset.container.workdir }}/license/axoniq.license
          subPath: axoniq.license
          readOnly: true
        {{ if $.Values.axoniq.axonserver.logbackBase64 }}
        - name: logback
          mountPath: {{$.Values.statefulset.container.workdir }}/config/logback.xml
          subPath: logback.xml
        {{ end }}
        {{ if $.Values.axoniq.axonserver.recoveryFileBase64 }}
        - name: recovery-file
          mountPath: {{$.Values.statefulset.container.workdir }}/recovery.json
          subPath: recovery.json
        {{ end }}
        {{end}}
      
      volumes:
        {{range $k, $v := $.Values.volumeClaimTemplates.templates}}
        - name: {{ $k }}
          persistentVolumeClaim:
            claimName: {{ $k }}-{{$appName}}-{{ $counter }}-0
        {{ end }}

        {{if eq $.Values.app.platform "ee"}}
        - name: properties
          secret:
            secretName: axonserver-properties
        - name: cluster-template
          secret:
            secretName: axonserver-cluster-template
        - name: system-token
          secret:
            secretName: axonserver-system-token
        - name: license
          secret:
            secretName: axonserver-license
        {{ if $.Values.axoniq.axonserver.logbackBase64}}
        - name: logback
          secret:
            secretName: axonserver-logback
        {{ end }}
        {{ if $.Values.axoniq.axonserver.recoveryFileBase64 }}
        - name: recovery-file
          secret:
            secretName: axonserver-recovery-file
        {{ end }}
        {{end}}
  {{ if $.Values.volumeClaimTemplates.templates }}
  volumeClaimTemplates:
  {{ end }}
  {{range $k, $v := $.Values.volumeClaimTemplates.templates }}
    - metadata:
        namespace: {{ $.Release.Namespace }}
        name: {{ $k }}
      spec:
        accessModes: {{ $v.accessModes | default $.Values.volumeClaimTemplates.defaults.accessModes | toYaml | nindent 10 }}
        {{ if $.Values.aws.azs }}
        {{ with index $.Values.aws.azs $counter }}
        storageClassName: {{ $appName }}-{{ $.Release.Namespace }}-{{ . }}
        {{ end }}
        {{ else }}
        storageClassName: {{ $v.storageClassName | default $.Values.volumeClaimTemplates.defaults.storageClassName }}
        {{ end }}
        resources:
          requests:
            storage: {{ $v.storage | default $.Values.volumeClaimTemplates.defaults.storage }}
  {{end}}
{{ end }}
