{{- range untilStep 0 (int .Values.statefulset.count) 1 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.app.name}}-{{ . }}
  labels:
    app: {{$.Values.app.name}}
spec:
  podManagementPolicy: {{$.Values.statefulset.podManagementPolicy}}
  serviceName: {{$.Values.app.name}}-svc
  replicas: 1
  selector:
    matchLabels:
      app: {{$.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{$.Values.app.name}}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      {{- with index $.Values.aws.azs . }}
      nodeSelector:
        topology.kubernetes.io/zone: {{ . }}
      {{- end }}  
      containers:
      - name: {{$.Values.app.name}}
        image: {{$.Values.statefulset.container.image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{$.Values.resources.limits.cpu}}
            memory: {{$.Values.resources.limits.memory}}
          requests:
            cpu: {{$.Values.resources.requests.cpu}}
            memory: {{$.Values.resources.requests.cpu}}
        ports:
        - name: grpc
          containerPort: {{$.Values.service.ports.grpc}}
          protocol: TCP
        - name: gui
          containerPort: {{$.Values.service.ports.gui}}
          protocol: TCP
        {{if eq $.Values.app.platform "ee"}}
        env:
        {{- range $.Values.statefulset.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        - name: AXONIQ_LICENSE
          value: {{$.Values.statefulset.container.workdir }}/license/axoniq.license
        {{end}}
        volumeMounts:
        - name: log
          mountPath: {{$.Values.statefulset.container.workdir }}/log
        
        - name: data
          mountPath: {{$.Values.statefulset.container.workdir }}/data

        - name: events
          mountPath: {{$.Values.statefulset.container.workdir }}/events

        - name: exts
          mountPath: {{$.Values.statefulset.container.workdir }}/exts

        - name: plugins
          mountPath: {{$.Values.statefulset.container.workdir }}/plugins

        - name: snapshots
          mountPath: {{$.Values.statefulset.container.workdir }}/snapshots

        {{if eq $.Values.app.platform "ee"}}  
        - name: properties
          mountPath: {{$.Values.statefulset.container.workdir }}/config/axonserver.properties
          subPath: axonserver.properties
          readOnly: true
        - name: cluster-template
          mountPath: {{$.Values.statefulset.container.workdir }}/config/cluster-template.yaml
          subPath: cluster-template.yaml
          readOnly: true
        - name: system-token
          mountPath: {{$.Values.statefulset.container.workdir }}/security/axoniq.token
          subPath: axoniq.token
          readOnly: true
        - name: license
          mountPath: {{$.Values.statefulset.container.workdir }}/license/axoniq.license
          subPath: axoniq.license
          readOnly: true
        {{ if $.Values.axoniq.axonserver.recoveryFileBase64 }}
        - name: recovery-file
          mountPath: {{$.Values.statefulset.container.workdir }}/recovery.json
          subPath: recovery.json
        {{ end }}
        {{end}}

        readinessProbe:
          tcpSocket:
            port: {{ $.Values.service.ports.gui }}
          initialDelaySeconds: {{$.Values.statefulset.readiness.initialDelaySeconds}}
          periodSeconds: {{$.Values.statefulset.readiness.periodSeconds}}
          timeoutSeconds: {{$.Values.statefulset.readiness.timeoutSeconds}}
          failureThreshold: {{$.Values.statefulset.readiness.failureThreshold}}
        livenessProbe:
          tcpSocket:
            port: {{ $.Values.service.ports.gui }}
          initialDelaySeconds: {{$.Values.statefulset.liveness.initialDelaySeconds}}
          periodSeconds: {{$.Values.statefulset.liveness.periodSeconds}}
          timeoutSeconds: {{$.Values.statefulset.liveness.timeoutSeconds}}
          successThreshold: {{$.Values.statefulset.liveness.successThreshold}}
          failureThreshold: {{$.Values.statefulset.liveness.failureThreshold}}
      volumes:
        - name: log
          emptyDir: {}
    
        - name: data
          {{ if not $.Values.volumeClaimTemplates.data.enabled }}
          emptyDir: {}
          {{ else if and ($.Values.volumeClaimTemplates.data.enabled) ($.Values.volumeClaimTemplates.data.volumeIds) }}
          persistentVolumeClaim: 
            claimName: data-{{$.Values.app.name}}-{{ . }}
          {{ end }}

        - name: events
          {{ if not $.Values.volumeClaimTemplates.events.enabled }}
          emptyDir: {}
          {{ else if and ($.Values.volumeClaimTemplates.events.enabled) ($.Values.volumeClaimTemplates.events.volumeIds) }}
          persistentVolumeClaim: 
            claimName: events-{{$.Values.app.name}}-{{ . }}
          {{ end }}

        - name: exts
          {{ if not $.Values.volumeClaimTemplates.exts.enabled }}
          emptyDir: {}
          {{ else if and ($.Values.volumeClaimTemplates.exts.enabled) ($.Values.volumeClaimTemplates.exts.volumeIds) }}
          persistentVolumeClaim: 
            claimName: exts-{{$.Values.app.name}}-{{ . }}
          {{ end }}

        - name: plugins
          {{ if not $.Values.volumeClaimTemplates.plugins.enabled }}
          emptyDir: {}
          {{ else if and ($.Values.volumeClaimTemplates.plugins.enabled) ($.Values.volumeClaimTemplates.plugins.volumeIds) }}
          persistentVolumeClaim: 
            claimName: plugins-{{$.Values.app.name}}-{{ . }}
          {{ end }}

        - name: snapshots
          {{ if not $.Values.volumeClaimTemplates.snapshots.enabled }}
          emptyDir: {}
          {{ else if and ($.Values.volumeClaimTemplates.snapshots.enabled) ($.Values.volumeClaimTemplates.snapshots.volumeIds) }}
          persistentVolumeClaim: 
            claimName: snapshots-{{$.Values.app.name}}-{{ . }}
          {{ end }}

        {{if eq $.Values.app.platform "ee"}}  
        - name: properties
          secret:
            secretName: axonserver-properties
        - name: cluster-template
          secret:
            secretName: axonserver-cluster-template
        - name: system-token
          secret:
            secretName: axonserver-system-token
        - name: license
          secret:
            secretName: axonserver-license
        {{ if $.Values.axoniq.axonserver.recoveryFileBase64 }}    
        - name: recovery-file
          secret:
            secretName: axonserver-recovery-file
        {{ end }}
        {{end}}
  {{- range $v := $.Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    - metadata:
        namespace: {{ .Release.Namespace }}
        name: {{ $v.name}}-{{$.Values.app.name}}
      spec:
        accessModes:
          {{ toYaml $v.accessModes | nindent 10 }}
        storageClassName: {{ $v.storageClassName  }}
        resources:
          requests:
            storage: {{ $v.storage }}
    {{ end }}
  {{- end }}

{{- end }}
