apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.app.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  serviceName: {{.Values.app.name}}-grpc
  {{if eq .Values.app.platform "ee"}}
  replicas: {{.Values.statefulset.replicas}}
  {{else}}
  replicas: 1
  {{end}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      {{if eq .Values.app.platform "ee"}}
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      {{end}}
      containers:
      - name: {{.Values.app.name}}
        image: {{.Values.statefulset.container.image}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: {{ .Values.service.ports.grpc }}
          protocol: TCP
        - name: gui
          containerPort: {{ .Values.service.ports.gui }}
          protocol: TCP
        {{if eq .Values.app.platform "ee"}}
        env:
        - name: AXONIQ_LICENSE
          value: "{{ template "license.path" . }}/axoniq.license"
        {{end}}
        volumeMounts:
        - name: pid
          mountPath: {{ template "pid.path" . }}
        - name: log
          mountPath: {{ template "log.path" . }}
        - name: data
          mountPath: {{ template "data.path" . }}
        - name: snapshots
          mountPath: {{ template "snapshots.path" . }}
        - name: events
          mountPath: {{ template "events.path" . }}
        {{if eq .Values.app.platform "ee"}}  
        - name: config
          mountPath: {{ template "config.path" . }}
          readOnly: true
        - name: cluster-template
          mountPath: {{ template "config.path" . }}/cluster-template
          readOnly: true
        - name: system-token
          mountPath: {{ template "systemToken.path" . }}
          readOnly: true
        - name: license
          mountPath: {{ template "license.path" . }}
          readOnly: true
        {{end}}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.ports.gui }}
          initialDelaySeconds: {{.Values.statefulset.readiness.initialDelaySeconds}}
          periodSeconds: {{.Values.statefulset.readiness.periodSeconds}}
          timeoutSeconds: {{.Values.statefulset.readiness.timeoutSeconds}}
          failureThreshold: {{.Values.statefulset.readiness.failureThreshold}}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.ports.gui }}
          initialDelaySeconds: {{.Values.statefulset.liveness.initialDelaySeconds}}
          periodSeconds: {{.Values.statefulset.liveness.periodSeconds}}
          timeoutSeconds: {{.Values.statefulset.liveness.timeoutSeconds}}
          successThreshold: {{.Values.statefulset.liveness.successThreshold}}
          failureThreshold: {{.Values.statefulset.liveness.failureThreshold}}
      volumes:
        - name: pid
          emptyDir: {}
        - name: log
          emptyDir: {}
        {{if eq .Values.app.platform "ee"}}  
        - name: config
          secret:
            secretName: axonserver-properties
        - name: cluster-template
          secret:
            secretName: axonserver-cluster-template
        - name: system-token
          secret:
            secretName: axonserver-token
        - name: license
          secret:
            secretName: axonserver-license
        {{end}}
  volumeClaimTemplates:
    - metadata:
        name: events
      spec:
        accessModes:
          {{ toYaml .Values.volumeClaimTemplates.events.accessModes | indent 10 }}
        resources:
          requests:
            storage: {{.Values.volumeClaimTemplates.events.storage}}
    - metadata:
        name: data
      spec:
        accessModes:
          {{ toYaml .Values.volumeClaimTemplates.data.accessModes | indent 10 }}
        resources:
          requests:
            storage: {{.Values.volumeClaimTemplates.data.storage}}
    - metadata:
        name: snapshots
      spec:
        accessModes: 
          {{ toYaml .Values.volumeClaimTemplates.snapshots.accessModes | indent 10 }}
        resources:
          requests:
            storage: {{.Values.volumeClaimTemplates.snapshots.storage}}
