{{ range untilStep 0 (int .Values.statefulset.count) 1 }}
{{ $counter := . }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.app.name}}-{{ $counter }}
  labels:
    app: {{$.Values.app.name}}
spec:
  podManagementPolicy: {{$.Values.statefulset.podManagementPolicy}}
  serviceName: {{$.Values.app.name}}-svc
  replicas: 1
  selector:
    matchLabels:
      app: {{$.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{$.Values.app.name}}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      nodeSelector:
      {{ if $.Values.aws.azs }}
        {{ with index $.Values.aws.azs $counter }}
        topology.kubernetes.io/zone: {{ $counter }}
        {{ end }} 
      {{ else }}
        {{- toYaml $.Values.nodeSelector | indent 2 }}
      {{ end }} 
      containers:
      - name: {{$.Values.app.name}}
        image: {{$.Values.statefulset.container.image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{$.Values.resources.limits.cpu}}
            memory: {{$.Values.resources.limits.memory}}
          requests:
            cpu: {{$.Values.resources.requests.cpu}}
            memory: {{$.Values.resources.requests.cpu}}
        ports:
        - name: grpc
          containerPort: {{$.Values.service.ports.grpc}}
          protocol: TCP
        - name: gui
          containerPort: {{$.Values.service.ports.gui}}
          protocol: TCP
        {{if eq $.Values.app.platform "ee"}}
        env:
        {{ range $.Values.statefulset.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{ end }}
        - name: AXONIQ_LICENSE
          value: {{$.Values.statefulset.container.workdir }}/license/axoniq.license
        {{end}}
        volumeMounts:
        - name: logs
          mountPath: {{$.Values.statefulset.container.workdir }}/log
        
        - name: data
          mountPath: {{$.Values.statefulset.container.workdir }}/data

        - name: events
          mountPath: {{$.Values.statefulset.container.workdir }}/events

        - name: exts
          mountPath: {{$.Values.statefulset.container.workdir }}/exts

        - name: plugins
          mountPath: {{$.Values.statefulset.container.workdir }}/plugins

        - name: snapshots
          mountPath: {{$.Values.statefulset.container.workdir }}/snapshots

        {{if eq $.Values.app.platform "ee"}}  
        - name: properties
          mountPath: {{$.Values.statefulset.container.workdir }}/config/axonserver.properties
          subPath: axonserver.properties
          readOnly: true
        - name: cluster-template
          mountPath: {{$.Values.statefulset.container.workdir }}/config/cluster-template.yaml
          subPath: cluster-template.yaml
          readOnly: true
        - name: system-token
          mountPath: {{$.Values.statefulset.container.workdir }}/security/axoniq.token
          subPath: axoniq.token
          readOnly: true
        - name: license
          mountPath: {{$.Values.statefulset.container.workdir }}/license/axoniq.license
          subPath: axoniq.license
          readOnly: true
        {{ if $.Values.axoniq.axonserver.recoveryFileBase64 }}
        - name: recovery-file
          mountPath: {{$.Values.statefulset.container.workdir }}/recovery.json
          subPath: recovery.json
        {{ end }}
        {{end}}

        readinessProbe:
          tcpSocket:
            port: {{ $.Values.service.ports.gui }}
          initialDelaySeconds: {{$.Values.statefulset.readiness.initialDelaySeconds}}
          periodSeconds: {{$.Values.statefulset.readiness.periodSeconds}}
          timeoutSeconds: {{$.Values.statefulset.readiness.timeoutSeconds}}
          failureThreshold: {{$.Values.statefulset.readiness.failureThreshold}}
        livenessProbe:
          tcpSocket:
            port: {{ $.Values.service.ports.gui }}
          initialDelaySeconds: {{$.Values.statefulset.liveness.initialDelaySeconds}}
          periodSeconds: {{$.Values.statefulset.liveness.periodSeconds}}
          timeoutSeconds: {{$.Values.statefulset.liveness.timeoutSeconds}}
          successThreshold: {{$.Values.statefulset.liveness.successThreshold}}
          failureThreshold: {{$.Values.statefulset.liveness.failureThreshold}}
      volumes:
        {{range $k, $v := $.Values.volumeClaimTemplates.templates}}
        - name: {{ $k }}
          {{ if $v.enabled }}
          persistentVolumeClaim: 
            claimName: {{ $k }}-{{$.Values.app.name}}-{{ $counter }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        {{end}}

        {{if eq $.Values.app.platform "ee"}}  
        - name: properties
          secret:
            secretName: axonserver-properties
        - name: cluster-template
          secret:
            secretName: axonserver-cluster-template
        - name: system-token
          secret:
            secretName: axonserver-system-token
        - name: license
          secret:
            secretName: axonserver-license
        {{ if $.Values.axoniq.axonserver.recoveryFileBase64 }}    
        - name: recovery-file
          secret:
            secretName: axonserver-recovery-file
        {{ end }}
        {{end}}
  {{range $k, $v := $.Values.volumeClaimTemplates.templates}}
  volumeClaimTemplates:
    {{ if $v.enabled }}
    - metadata:
        namespace: {{ $.Release.Namespace }}
        name: {{ $k }}-{{ $.Values.app.name }}
      spec:
        accessModes:
          {{ $v.accessModes | default $.Values.volumeClaimTemplates.defaults.accessModes | toYaml | nindent 10 }}
        storageClassName: {{ $v.storageClassName | default $.Values.volumeClaimTemplates.defaults.storageClassName }}
        resources:
          requests:
            storage: {{ $v.storage | default $.Values.volumeClaimTemplates.defaults.storage }}
    {{ end }}
  {{end}}

{{ end }}
