{{- range .Values.issuers -}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    email: {{ .email }}
    server: {{ .server }}
    privateKeySecretRef:
      name: {{ .privateKeySecretRef.name }}
    solvers:
      {{ .solvers | toYaml | indent 6 | trim }}
{{ end }}
